
server:
  error:
    whitelabel:
      enabled: false

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:apples;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  application:
    name: springboot-employee-service

# Access H2 console as follows -> http://localhost:8080/h2-console/
# Use JDBC URL as follows when you define database name = "apples"
# jdbc:h2:mem:apples

security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false
  info:
    git:
      mode: full
  cloudfoundry:
    skip-ssl-validation: true
  endpoints:
    actuator:
      sensitive: false